### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by benpm** [Lemoncreme/opengl-museum#1]
- [x] Zoomable orthographic projection such that museum model can be loaded in at any scale
- [ ] Get  vertex colors to work
- [x] Add textures to museum model
- [x] Use camera.h, mesh.h, model.h and shader.h
