### ISSUE TITLE
Rubric Todo

### ISSUE THREAD

**Issue by benpm** [Lemoncreme/opengl-museum#2]
### Github Organization (20 pts)

- [x] Museum executable
- [x] Folder containing project code
- [x] Folder containing models
- [x] museum
- [x] sculpture
- [x] frame/portrait
- [x] Folder containing textures

### Code (40 pts)

- [x] Utilizes OOP
- [x] Model Loader
- [x] Camera
- [x] Shader
- [x] Meaningful comments throughout
- [ ] ~Orthographic View Implemented~
- [x] Compiles (10 pt)/Executes without Errors (10 pt)

### Museum (40 pts)

- [x] at least one Sculpture
- [x] Museum model has floors/walls
- [x] at least 4 paintings
- [x] Textures applied throughout
- [x] Museum building
- [x] Sculpture
- [x] Paintings
- [x] Lighting

### Bonus

- [x] Assimp utilized for model loading (+2)
- [x] Perspective View Implemented (+2)
- [x] Additional unique sculptures (+1 / additional : max +3)
- [x] Additional unique paintings (+1 / additional : max +3)
